config/routes.rb
#
# Application routes file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

Rails.application.routes.draw do

  # Provide a route for robots.txt.
  mount_roboto

  # Provide the Devise routes.
  devise_for :users,
             path:        '',
             path_names:  { sign_in:      'login',
                            sign_out:     'logout',
                            registration: 'registration',
                            sign_up:      'sign_up_account' },
             controllers: { registrations: 'users/registrations' }

  # Define the home, about and privacy pages.  Note that root is especially needed for Devise.
  get 'home', to: 'home#home', as: 'home'
  get 'about', to: 'home#about', as: 'about'
  get 'documents', to: 'home#documents', as: 'documents'
  get 'introduction', to: 'home#introduction', as: 'introduction'
  get 'privacy', to: 'home#privacy', as: 'privacy'
  get 'verifiable', to: 'home#verifiable', as: 'verifiable'
  root to: redirect(path: '/home')

  # Define user account pages.
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :invitations, except: [:show]

  # Define service pages.
  resources :services, only: [:edit, :update]

  # Define election pages and associated data.
  resources :audit_logs, only: [:index]
  resources :file_types
  resources :elections
  resources :uploads, except: [:destroy] do
    resources :contents, shallow: true, only: [:index, :show]
    member do
      get :blockchain
      get :download
      post :recommit
      post :retrieve
    end
  end

  # Define the voter verification routes.
  get 'verify', to: 'verify#verify'
  get 'verify/status', to: 'verify#status'
  get 'verify/faq', to: 'verify#faq'
  get 'verify/report_my_vote', to: 'verify#report_my_vote'
  post 'verify/send_report', to: 'verify#send_report'

  # Match certbot challenge responses.
  get '/.well-known/acme-challenge/*file', to: 'home#challenge', as: 'challenge'

  # Catch anything else and send it to the UI root, unless in development mode. Note that we explicitly ignore ActiveStorage as its routes are added afterwards.
  unless Rails.env.development?
    match "*path", to: 'application#not_found', via: :all, constraints: lambda { |request|
      request.path.exclude? 'rails/active_storage'
    }
  end
end

app/views/shared/_breadcrumb.html.haml
- unless request.path == home_path
  - add_breadcrumb t('shared.titles.home'), :home_path
  .container
    %nav{ aria: { label: t('shared.titles.breadcrumb')} }
      %ol.breadcrumb
        = render_breadcrumbs tag: :li, separator: '', builder: BootstrapBreadcrumbsBuilder, current_path: request.path

app/views/shared/_cookie_notice.html.haml
- if !cookies[:dismiss_cookie_notice] && !user_signed_in?
  - cache @virtual_path, skip_digest: true do
    #cookie-notice
      .container-fluid#cookie-content
        .row
          .col-sm-7.col-md-8
            %p.my-1= t('.cookie_notice')
          .col-sm-5.col-md-4
            %p.my-1.text-right= link_to t('.cookie_ok'), 'javascript:void(0)', class: 'btn btn-success', data: { 'dismiss-cookie-notice' => true, target: '#cookie-notice' }
            %p.my-1.text-right= link_to t('.find_out'), privacy_path(anchor: 'cookies')

app/views/shared/_footer.html.haml
- cache [@virtual_path, Date.today], skip_digest: true do
  %footer
    .container
      %section#quick_links
        %nav.text-center
          = link_to t('shared.titles.home'), root_path
          = '|'
          = link_to t('shared.titles.privacy'), privacy_path
          = '|'
          = link_to t('shared.titles.login'), new_user_session_path

      %section#copyright
        %p.text-center= t('.copyright_html', year: Date.today.year, copyright: link_to(t('.copyright').html_safe, t('surrey_web')))

app/views/shared/_form_buttons.html.haml
= form.form_group do
  = link_to t('shared.controls.cancel'), :back, class: 'btn btn-primary'
  = form.button t('shared.controls.reset'), render_as_button: true, type: 'reset', class: 'btn btn-primary'
  = form.submit t('shared.controls.save'), class: 'btn btn-primary'

app/views/shared/_form_mandatory.html.haml
= form.form_group do
  %span= t('shared.controls.mandatory')

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-expand-md.navbar-light.navbar-bg.fixed-top
    .container
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'surrey.png', alt: t('surrey'), title: t('surrey')
      %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#navbar', aria: { controls: 'navbar', expanded: false, label: t('shared.controls.toggle') } } }
        %span.navbar-toggler-icon

      #navbar.navbar-collapse.collapse
        - if content_for? :menu
          = yield :menu

app/views/shared/_list_buttons.html.haml
- css_class = defined?(options) ? options[:css_class] : ''
- show_edit = defined?(options) ? options[:show_edit] : true
- show_edit ||= true
- show_destroy = defined?(options) ? options[:show_destroy] : true
- show_destroy ||= true

.text-nowrap
  - if show_edit && model && policy(model).edit?
    = link_to send("edit_#{model.model_name.singular}_path", model), class: css_class do
      = fa_icon 'pencil-alt lg', title: t('shared.controls.edit'), class: css_class
      %span.sr-only= t('shared.controls.edit')

  - if show_destroy && model && name && policy(model).destroy?
    = link_to url_for(model), method: :delete, data: { confirm: t('shared.controls.confirm_destroy', model: model.model_name.singular.humanize.downcase, name: name) }, class: css_class do
      = fa_icon 'trash-alt lg', title: t('shared.controls.destroy'), class: css_class
      %span.sr-only= t('shared.controls.destroy')

app/views/shared/_menu.html.haml
%ul.navbar-nav.mr-auto
  = link_to_list_active introduction_path do
    = t('shared.titles.introduction')
  = link_to_list_active verifiable_path do
    = t('shared.titles.verifiable')
  = link_to_list_active about_path do
    = t('shared.titles.about')
  = link_to_list_active documents_path do
    = t('shared.titles.documents')
  - if policy(Election).index?
    = link_to_list_active elections_path do
      = t('shared.titles.elections')

%ul.navbar-nav
  - if user_signed_in?
    = render 'shared/menu_admin'

  - if (defined?(@show_account) && @show_account) || user_signed_in?
    = render 'shared/menu_account'

app/views/shared/_menu_account.html.haml
%li.nav-item.dropdown
  = link_to '#', class: 'nav-link dropdown-toggle', id: 'navbar_account', role: 'button', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } do
    %span.hide-when-collapsed
      = fa_icon 'user lg', title: t('.account')
    %span.hide-when-not-collapsed
      = fa_icon 'user lg fw', title: t('.account')
      - if user_signed_in?
        = t('.account')
      - else
        = t('shared.titles.login')

  .dropdown-menu.dropdown-menu-right{ aria: { labelledby: "navbar_account" } }
    - if user_signed_in?
      %p.pl-3.text-nowrap.text-muted= current_user.fullname

      = link_to_active edit_user_registration_path do
        = fa_icon 'edit fw'
        = t('.edit')

      = link_to_active destroy_user_session_path, method: 'delete' do
        = fa_icon 'sign-out-alt fw'
        = t('.logout')

    - else
      = link_to_active new_user_session_path do
        = fa_icon 'sign-in-alt fw'
        = t('shared.titles.login')

      .dropdown-divider

      = link_to_active new_user_registration_path do
        = fa_icon 'sign-in-alt fw'
        = t('.sign_up')

      = link_to_active new_user_password_path do
        = fa_icon 'unlock-alt fw'
        = t('.forgotten_password')

      = link_to_active new_user_confirmation_path do
        = fa_icon 'paper-plane fw'
        = t('.resend_confirmation')

      = link_to_active new_user_unlock_path do
        = fa_icon 'paper-plane fw'
        = t('.resend_unlock')

app/views/shared/_menu_admin.html.haml
- if current_user.administrator?
  %li.nav-item.dropdown
    = link_to '#', class: 'nav-link dropdown-toggle', id: 'navbar_admin', role: 'button', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } do
      %span.hide-when-collapsed
        = fa_icon 'cogs lg', title: t('.administration')
      %span.hide-when-not-collapsed
        = fa_icon 'cogs lg fw', title: t('.administration')
        = t('.administration')

    .dropdown-menu.dropdown-menu-right{ aria: { labelledby: "navbar_admin" } }
      %p.pl-3.text-nowrap.text-muted= t('.services')

      - if policy(Service).edit?
        - service = Service.get_service
        = link_to_active edit_service_path(service), class: "#{service.ui_enabled? && service.jobs_enabled? ? '' : 'bg-muted-danger'}" do
          = fa_icon 'cog fw'
          = t('.service')

      - if policy(FileType).index?
        = link_to_active file_types_path do
          = fa_icon 'file fw'
          = t('.file_types')

      - if policy(AuditLog).index?
        = link_to_active audit_logs_path do
          = fa_icon 'check-square fw'
          = t('.audit_logs')

      .dropdown-divider
      %p.pl-3.text-nowrap.text-muted= t('.election_data')

      - if policy(Election).index?
        = link_to_active elections_path do
          = fa_icon 'cog fw'
          = t('.elections')

      - if policy(Upload).index?
        = link_to_active uploads_path do
          = fa_icon 'file fw'
          = t('.uploads')

      .dropdown-divider
      %p.pl-3.text-nowrap.text-muted= t('.accounts')

      - if policy(User).index?
        = link_to_active users_path do
          = fa_icon 'users fw'
          = t('.users')

      - if policy(Invitation).index?
        = link_to_active invitations_path do
          = fa_icon 'envelope fw'
          = t('.invitations')

app/views/shared/_notice.html.haml
- flash.each do |key, value|
  - if !value.blank? && value.is_a?(String)
    .container
      .alerts
        .alert.alert-dismissible.fade.show.lead{ role: 'alert', class: "alert-#{key == 'alert' ? 'danger' : 'info'}"}
          = value
          = button_tag type: 'button', class: 'close', 'data-dismiss' => 'alert', 'aria-label' => t('shared.controls.close') do
            %span{'aria-hidden' => 'true'} &times;

- model = nil
- model = resource if defined?(resource)
- model = @model if defined?(@model) && !@model.nil? && !defined?(resource)
- unless model.nil?
  - unless model.errors.empty?
    - messages = model.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    - sentence = t("errors.messages.not_saved", count: model.errors.count, resource: model.class.model_name.human.downcase)

    .container
      .alerts
        .alert.alert-danger.alert-dismissible.fade.show.lead{role: 'alert'}
          = button_tag type: 'button', class: 'close', 'data-dismiss' => 'alert', 'aria-label' => t('shared.controls.close') do
            %span{'aria-hidden' => 'true'} &times;
          != sentence
          %ul
            != messages

app/views/shared/_scroll_top.html.haml
= button_tag t('shared.titles.scroll_to_top'), id: 'scroll-top', class: 'd-none btn btn-transparent btn-bottom fixed-bottom'
:javascript
  VMV.ScrollTop.scrollTop('#scroll-top');

app/views/shared/_show_buttons.html.haml
- show_edit = defined?(options) ? options[:show_edit] : true
- show_edit ||= true
- show_destroy = defined?(options) ? options[:show_destroy] : true
- show_destroy ||= true

= form.form_group do
  = link_to t('shared.controls.back'), :back, class: 'btn btn-primary'

  - if show_edit && defined?(model) && model && policy(model).edit?
    = link_to t('shared.controls.edit'), send("edit_#{model.model_name.singular}_path", model), class: 'btn btn-primary'

  - if show_destroy && defined?(model) && model && name && policy(model).destroy?
    = link_to t('shared.controls.destroy'), url_for(model), method: :delete, data: { confirm: t('shared.controls.confirm_destroy', model: model.model_name.singular.humanize.downcase, name: name) }, class: 'btn btn-danger'