config/routes.rb
#
# Application routes file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

Rails.application.routes.draw do

  # Provide a route for robots.txt.
  mount_roboto

  # Provide the Devise routes.
  devise_for :users,
             path:        '',
             path_names:  { sign_in:      'login',
                            sign_out:     'logout',
                            registration: 'registration',
                            sign_up:      'sign_up_account' },
             controllers: { registrations: 'users/registrations' }

  # Define the home, about and privacy pages.  Note that root is especially needed for Devise.
  get 'home', to: 'home#home', as: 'home'
  get 'about', to: 'home#about', as: 'about'
  get 'documents', to: 'home#documents', as: 'documents'
  get 'introduction', to: 'home#introduction', as: 'introduction'
  get 'privacy', to: 'home#privacy', as: 'privacy'
  get 'verifiable', to: 'home#verifiable', as: 'verifiable'
  root to: redirect(path: '/home')

  # Define user account pages.
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :invitations, except: [:show]

  # Define service pages.
  resources :services, only: [:edit, :update]

  # Define election pages and associated data.
  resources :audit_logs, only: [:index]
  resources :file_types
  resources :elections
  resources :uploads, except: [:destroy] do
    resources :contents, shallow: true, only: [:index, :show]
    member do
      get :blockchain
      get :download
      post :recommit
      post :retrieve
    end
  end

  # Define the voter verification routes.
  get 'verify', to: 'verify#verify'
  get 'verify/status', to: 'verify#status'
  get 'verify/faq', to: 'verify#faq'
  get 'verify/report_my_vote', to: 'verify#report_my_vote'
  post 'verify/send_report', to: 'verify#send_report'

  # Match certbot challenge responses.
  get '/.well-known/acme-challenge/*file', to: 'home#challenge', as: 'challenge'

  # Catch anything else and send it to the UI root, unless in development mode. Note that we explicitly ignore ActiveStorage as its routes are added afterwards.
  unless Rails.env.development?
    match "*path", to: 'application#not_found', via: :all, constraints: lambda { |request|
      request.path.exclude? 'rails/active_storage'
    }
  end
end

app/models/election.rb
#
# Election model file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

class Election < ApplicationRecord
  include Public

  # Associations.
  has_many :uploads, inverse_of: :election, dependent: :restrict_with_error

  # Validators.
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :survey_url, url: true, unless: -> { self.survey_url.blank? }

  # Scopes.
  scope :recent, -> { order(created_at: :desc).limit(3) }
  scope :election_map_select, -> { order(name: :asc).map { |election| [election.name, election.id] } }

  #
  # @return If the election has voter status available.
  #
  def status?
    # Any one file is enough.
    available = self.uploads.joins(:file_type).where('file_types.public = uploads.public AND needed_for_status = ?', true).count >= 1
    retrieved = self.uploads.joins(:file_type).where('uploads.public = ? AND needed_for_status = ? AND retrieved_at IS NOT NULL', true, true).count >= 1

    available && retrieved
  end

  #
  # @return If the election has voter verification available.
  #
  def verification?
    # All must be available.
    all_file_types = FileType.where(needed_for_verify: true)
    available      = self.uploads.joins(:file_type).where('file_types.public = uploads.public AND needed_for_verify = ?', true).count == all_file_types.count

    public_file_types = FileType.where(needed_for_verify: true, public: true)
    retrieved         = self.uploads.joins(:file_type).where('uploads.public = ? AND needed_for_verify = ? AND retrieved_at IS NOT NULL', true, true).count == public_file_types.count

    available && retrieved
  end
end

app/controllers/elections_controller.rb
#
# Elections controller class.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

class ElectionsController < ApplicationController
  before_action :set_election, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_show_account, except: [:index, :show]

  #
  # GET /elections
  # GET /elections.js
  #
  def index
    @elections = policy_scope(Election).order(sort_column.to_s + ' ' + sort_direction.to_s).page(params[:page]).per(params[:limit])
    authorize @elections
  end

  #
  # GET /elections/1
  # GET /elections/1.js
  #
  def show
    authorize @election

    # Setup the uploads for the selected election.
    @uploads = @election.uploads.is_public.is_success.joins(:file_type).order(sort_column.to_s + ' ' + sort_direction.to_s)
  end

  #
  # GET /elections/new
  #
  def new
    @election = Election.new
    authorize @election
  end

  #
  # GET /elections/1/edit
  #
  def edit
    authorize @election
  end

  #
  # POST /elections
  #
  def create
    @election = Election.new(election_params)
    authorize @election

    respond_to do |format|
      if @election.save
        format.html { redirect_to elections_url, notice: I18n.t('shared.messages.created') }
      else
        format.html { render :new }
      end
    end
  end

  #
  # PATCH/PUT /elections/1
  #
  def update
    authorize @election

    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to elections_url, notice: I18n.t('shared.messages.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  #
  # DELETE /elections/1
  #
  def destroy
    authorize @election

    respond_to do |format|
      if @election.destroy
        format.html { redirect_to elections_url, notice: I18n.t('shared.messages.destroyed') }
      else
        format.html { redirect_to elections_url, alert: I18n.t('shared.messages.not_destroyed') }
      end
    end
  end

  private

  #
  # Setup the resource.
  #
  def set_election
    @election = Election.find(params[:id])
  end

  #
  # Never trust parameters from the scary Internet, only allow the white list through.
  #
  def election_params
    params.require(:election).permit(:name, :public, :survey_url, :description)
  end

  #
  # Add in helper method for sort column.
  #
  helper_method :sort_column

  #
  # @returns The sort column.
  #
  def sort_column
    if action_name.to_sym == :index
      Election.column_names.include?(params[:sort].to_s) ? params[:sort].to_sym : :name
    else
      column = Upload.column_names.include?(params[:sort].to_s) ? params[:sort].to_sym : 'file_types.sequence'.to_sym

      # Deal with the join table.
      table_columns = params[:sort].to_s.split('.')
      column        = FileType.column_names.include?(table_columns[1].to_s) ? params[:sort].to_sym : column if table_columns.size >= 2 && table_columns[0] == FileType.table_name

      column
    end
  end
end

app/views/elections/_election.html.haml
= bootstrap_form_for(election, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |form|
  = form_field(form, :text_field, :name, autofocus: true, disabled: true)
  = form_field(form, :text_field, :description, disabled: true)
  = form.form_group do
    = form_field(form, :check_box, :public, disabled: true)
  = form_field(form, :url_field, :survey_url, disabled: true)

  = render partial: 'shared/show_buttons', locals: { form: form, model: election, name: election.name }

app/views/elections/_form.html.haml
- set_page_model(election)
= bootstrap_form_for(election, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |form|
  = form_field(form, :text_field, :name, autofocus: true)
  = form_field(form, :text_field, :description)
  = form.form_group do
    = form_field(form, :check_box, :public)
  = form_field(form, :url_field, :survey_url)

  = render partial: 'shared/form_mandatory', locals: { form: form }
  = render partial: 'shared/form_buttons', locals: { form: form }

app/views/elections/_list.html.haml
- if elections.count > 0
  = paginate elections, count: elections.total_count, remote: true
  %p.d-flex.flex-wrap.align-items-center.justify-content-end.h-100
    %span.small= t('shared.controls.sort')
    %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:name, t('activerecord.attributes.election.name'))
    %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:updated_at, t('activerecord.attributes.election.updated_at'))
  .row
    - elections.each do |election|
      .col-lg-4.col-md-6.col-12.my-3
        .card.text-white{ class: election.public? ? 'bg-primary' : 'bg-muted-primary' }
          .card-header.d-flex.justify-content-between
            %span= election.name
            = render partial: 'shared/list_buttons', locals: { model: election, name: election.name, options: { css_class: 'text-white no-decoration' } }
          .card-body.px-0
            %p.card-title.d-flex.flex-row.rounded.mx-1
              %span.description.col= election.description
            %p.card-title.d-flex.flex-row.rounded.mx-1
              %span.col-9.text-left= t('.data_available')
              %span.col-3.text-right= election.uploads.is_public.is_success.count > 0 ? t('shared.controls.yes') : t('shared.controls.no')
            %p.card-title.d-flex.flex-row.rounded.mx-1
              %span.col-9.text-left= t('.verification_available')
              %span.col-3.text-right= election.verification? ? t('shared.controls.yes') : t('shared.controls.no')
            %p.card-title.d-flex.flex-row.rounded.mx-1
              %span.col-6.text-left= t('activerecord.attributes.election.updated_at')
              %span.col-6.text-right= l(election.updated_at, format: :short) unless election.updated_at.nil?
            %p.card-title.d-flex.flex-row.mb-0
              %span.col.text-center= link_to t('.view'), election_path(election), class: 'btn btn-secondary p-0 w-100'
              - if user_signed_in?
                %span.col-4.text-center= link_to t('shared.controls.details'), uploads_path(filter: election.id), class: 'btn btn-secondary p-0 w-100'

app/views/elections/edit.html.haml
- specific_title [t('shared.controls.edit'), @election.name]
- add_breadcrumb "#{@election.name}: #{t('shared.controls.edit')}", request.path
- add_breadcrumb t('shared.titles.elections'), :elections_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= "#{t('shared.controls.edit')}: #{t('shared.titles.election')}"
  %p.lead= t('.instructions')

  = render partial: 'form', locals: { election: @election }

app/views/elections/index.html.haml
- specific_title [t('shared.titles.elections')]
- add_breadcrumb t('shared.titles.elections'), :elections_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1
    = t('shared.titles.elections')
    - if policy(Election).new?
      .float-right= link_to t('shared.controls.new'), new_election_path, class: 'btn btn-primary'

  - if @elections.count > 0
    %p.lead= t('.instructions')
  - else
    %p.lead= t('.no_elections')

.container#list
  = render partial: 'list', locals: { elections: @elections }

app/views/elections/index.js.erb
$('#list').html("<%= j render partial: 'list', locals: { elections: @elections } %>");

app/views/elections/new.html.haml
- specific_title [t('shared.controls.new'), t('shared.titles.election')]
- add_breadcrumb "#{t('shared.titles.election')}: #{t('shared.controls.new')}", request.path
- add_breadcrumb t('shared.titles.elections'), :elections_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= "#{t('shared.controls.new')}: #{t('shared.titles.election')}"
  %p.lead= t('.instructions')

  = render partial: 'form', locals: { election: @election }

app/views/elections/show.html.haml
- specific_title [@election.name, t('shared.titles.election')]
- add_breadcrumb @election.name, request.path
- add_breadcrumb t('shared.titles.elections'), :elections_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= @election.name
  - if user_signed_in?
    %p.lead= t('.instructions')
    = render partial: 'election', locals: { election: @election }
    %hr

  - unless @election.description.blank?
    %p.lead= @election.description

  - if @uploads.count > 0
    %p= t('.uploads_html', name: @election.name, url: link_to(t('.here'), asset_path('vmv.pdf')))
  - else
    %p= t('.no_uploads')

- FileType.stages.each do |stage|
  - uploads = @uploads.select { |upload| upload.file_type.stage.to_sym == stage[0].to_sym }
  - if uploads.size > 0
    .container
      %h2= t("activerecord.attributes.file_type.#{stage[0]}.name")
      %p.lead= t("activerecord.attributes.file_type.#{stage[0]}.description")
      = render partial: 'uploads/list_table', locals: { uploads: uploads, restricted: true, unsortable: true }

app/views/elections/show.js.erb
$('#list').html("<%= j render partial: 'uploads/list', locals: { uploads: @uploads, restricted: true } %>");