config/routes.rb
#
# Application routes file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

Rails.application.routes.draw do

  # Provide a route for robots.txt.
  mount_roboto

  # Provide the Devise routes.
  devise_for :users,
             path:        '',
             path_names:  { sign_in:      'login',
                            sign_out:     'logout',
                            registration: 'registration',
                            sign_up:      'sign_up_account' },
             controllers: { registrations: 'users/registrations' }

  # Define the home, about and privacy pages.  Note that root is especially needed for Devise.
  get 'home', to: 'home#home', as: 'home'
  get 'about', to: 'home#about', as: 'about'
  get 'documents', to: 'home#documents', as: 'documents'
  get 'introduction', to: 'home#introduction', as: 'introduction'
  get 'privacy', to: 'home#privacy', as: 'privacy'
  get 'verifiable', to: 'home#verifiable', as: 'verifiable'
  root to: redirect(path: '/home')

  # Define user account pages.
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :invitations, except: [:show]

  # Define service pages.
  resources :services, only: [:edit, :update]

  # Define election pages and associated data.
  resources :audit_logs, only: [:index]
  resources :file_types
  resources :elections
  resources :uploads, except: [:destroy] do
    resources :contents, shallow: true, only: [:index, :show]
    member do
      get :blockchain
      get :download
      post :recommit
      post :retrieve
    end
  end

  # Define the voter verification routes.
  get 'verify', to: 'verify#verify'
  get 'verify/status', to: 'verify#status'
  get 'verify/faq', to: 'verify#faq'
  get 'verify/report_my_vote', to: 'verify#report_my_vote'
  post 'verify/send_report', to: 'verify#send_report'

  # Match certbot challenge responses.
  get '/.well-known/acme-challenge/*file', to: 'home#challenge', as: 'challenge'

  # Catch anything else and send it to the UI root, unless in development mode. Note that we explicitly ignore ActiveStorage as its routes are added afterwards.
  unless Rails.env.development?
    match "*path", to: 'application#not_found', via: :all, constraints: lambda { |request|
      request.path.exclude? 'rails/active_storage'
    }
  end
end

app/controllers/verify_controller.rb
#
# Verify controller class.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

require 'openssl'

class VerifyController < ApplicationController
  before_action :authenticate_user!, only: []
  before_action :set_show_account, only: []
  before_action :set_election
  before_action :set_vote_record, except: [:status]
  before_action :set_voter_record, only: [:status]

  # Constants used in verification. Note that where appropriate, these values must match the corresponding file type database seeds in db/seeds.rb
  ELECTION_PARAMETERS = 'Election Parameters'.freeze
  P_FIELD             = 'p'.freeze

  VOTERS_KEYS       = "Voters' Keys".freeze
  PRIVATE_KEY_FIELD = 2

  ENCRYPTED_VOTERS = 'Encrypted Votes with Tracker Numbers'.freeze
  BETA_FIELD       = 'beta'.freeze
  PUBLIC_KEY_FIELD = 'publicKeyTrapdoor'.freeze

  TRACKER_NUMBERS               = 'Tracker Numbers'.freeze
  TRACKER_NUMBER_IN_GROUP_FIELD = 'trackerNumberInGroup'.freeze
  TRACKER_NUMBER_FIELD          = 'trackerNumber'.freeze

  MIXED_VOTERS = 'Final Votes'.freeze

  PUBLIC_VOTERS_KEYS   = 'Voter Public Keys with Encrypted Tracker Numbers'.freeze
  ENCRYPTED_VOTE_FIELD = 'encryptedVote'.freeze

  #
  # GET /verify/faq
  #
  def faq
    authorize @election
  end

  #
  # GET /verify/report_my_vote
  #
  def report_my_vote
    authorize @election
  end

  #
  # POST /verify/send_report
  #
  def send_report
    authorize @election

    beta     = nil
    beta     = params[:beta].to_i if params[:beta]
    tracker  = nil
    tracker  = params[:tracker].to_i if params[:tracker]
    election = params[:election]
    reason   = params[:reason]

    respond_to do |format|
      if (beta || tracker) && election
        UserMailer.report(election, beta, tracker, reason).deliver_later
        format.html { redirect_to root_path, notice: I18n.t('shared.messages.verify_report') }
      else
        format.html { redirect_to root_path, alert: I18n.t('shared.messages.verify_not_report') }
      end
    end
  end

  #
  # GET /verify/status
  #
  def status
    authorize @election

    respond_to do |format|
      format.html { render :status, status: @voter_record.nil? ? :accepted : :ok }
    end
  end

  #
  # GET /verify
  #
  def verify
    authorize @election

    respond_to do |format|
      format.html { render :verify, status: @vote_record.nil? ? :accepted : :ok }
    end
  end

  private

  #
  # Get the election parameter p from the publicly retrieved data.
  #
  # @return The election parameter p or nil if not found.
  #
  def get_p
    p = nil

    # Get the retrieved public election parameters file and the associated field.
    election_parameters = @election.uploads.find_by(file_type: FileType.find_by(name: ELECTION_PARAMETERS))

    if election_parameters
      p_field = election_parameters.field_name_to_sym(P_FIELD)

      if p_field
        record = election_parameters.contents.last
        p      = record[p_field].to_i if record && record[p_field]
      end
    end

    p
  end

  #
  # From the supplied public key, find the corresponding user's private trapdoor key from the privately held data.
  #
  # @param public_key The public key used to lookup the private key.
  # @return The corresponding private key or nil if not found.
  #
  def get_private_key(public_key)
    private_key = nil

    voters_keys = @election.uploads.find_by(file_type: FileType.find_by(name: VOTERS_KEYS))

    if voters_keys && voters_keys.file.attached?
      content = Rails.cache.fetch(voters_keys) do
        voters_keys.file.download
      end

      if content
        lines = content.lines
        found = lines.find { |line| /#{public_key}/ =~ line }

        if found
          elements    = found.split(',')
          private_key = elements[PRIVATE_KEY_FIELD].strip.gsub(/\A"|"\Z/, '').to_i if elements.length > PRIVATE_KEY_FIELD
        end
      end
    end

    private_key
  end

  #
  # From the supplied tracker number in the group, find the corresponding tracker number from the publicly retrieved data.
  #
  # @param beta The beta used to lookup the public key.
  # @return A hash containing the corresponding public key or nil if not found: { :public_key, :upload }
  #
  def get_public_key(beta)
    public_key = nil

    # Get the retrieved public encrypted voters file and the associated fields.
    encrypted_voters = @election.uploads.find_by(file_type: FileType.find_by(name: ENCRYPTED_VOTERS))

    if encrypted_voters
      beta_field       = encrypted_voters.field_name_to_sym(BETA_FIELD)
      public_key_field = encrypted_voters.field_name_to_sym(PUBLIC_KEY_FIELD)

      if beta_field && public_key_field
        record     = encrypted_voters.contents.find_by(beta_field => beta)
        public_key = record[public_key_field].to_i if record && record[public_key_field]
      end
    end

    { public_key: public_key, upload: encrypted_voters }
  end

  #
  # From the supplied beta, find the corresponding user's public trapdoor key from the publicly retrieved data.
  #
  # @param tracker_number_in_group The tracker number in the group used to lookup the tracker number.
  # @return A hash containing the corresponding tracker number or nil if not found: { :tracker_number, :upload }
  #
  def get_tracker_number(tracker_number_in_group)
    tracker_number = nil

    # Get the retrieved public tracker numbers file and the associated fields.
    tracker_numbers = @election.uploads.find_by(file_type: FileType.find_by(name: TRACKER_NUMBERS))

    if tracker_numbers
      tracker_number_in_group_field = tracker_numbers.field_name_to_sym(TRACKER_NUMBER_IN_GROUP_FIELD)
      tracker_number_field          = tracker_numbers.field_name_to_sym(TRACKER_NUMBER_FIELD)

      if tracker_number_in_group_field && tracker_number_field
        record         = tracker_numbers.contents.find_by(tracker_number_in_group_field => tracker_number_in_group)
        tracker_number = record[tracker_number_field].to_i if record && record[tracker_number_field]
      end
    end

    { tracker_number: tracker_number, upload: tracker_numbers }
  end


  #
  # From the supplied beta, find the corresponding encrypted vote from the publicly retrieved data.
  #
  # @param beta The beta used to lookup the public key.
  # @return True if a vote has been cast for this beta, false if no vote has been cast, and nil if voting has not been completed.
  #
  def get_vote_cast(beta)
    vote_cast = nil

    # Get the retrieved public encrypted voters file and the associated fields.
    encrypted_voters = @election.uploads.find_by(file_type: FileType.find_by(name: ENCRYPTED_VOTERS))

    if encrypted_voters
      beta_field           = encrypted_voters.field_name_to_sym(BETA_FIELD)
      encrypted_vote_field = encrypted_voters.field_name_to_sym(ENCRYPTED_VOTE_FIELD)

      if beta_field && encrypted_vote_field
        record    = encrypted_voters.contents.find_by(beta_field => beta)
        vote_cast = record && !record[encrypted_vote_field].blank?
      end
    end

    vote_cast
  end

  #
  # From the supplied tracker number, find the corresponding vote record from the publicly retrieved data.
  #
  # @param tracker_number The tracker number to lookup the vote.
  # @return A hash containing the corresponding vote record or nil if not found: { :vote_record, :voters_field_names, :upload }
  #
  def get_vote_record(tracker_number)
    vote_record        = nil
    voters_field_names = nil

    # Get the retrieved public mixed voters file and the associated field.
    voters = @election.uploads.find_by(file_type: FileType.find_by(name: MIXED_VOTERS), public: true)

    if voters
      voters_field_names   = voters.get_field_names
      tracker_number_field = voters.field_name_to_sym(TRACKER_NUMBER_FIELD)

      if tracker_number_field
        vote_record = voters.contents.find_by(tracker_number_field => tracker_number)
      end
    end

    { vote_record: vote_record, voters_field_names: voters_field_names, upload: voters }
  end

  #
  # From the supplied beta, find the corresponding voter record from the publicly retrieved data.
  #
  # @param beta The beta to lookup the voter.
  # @return A hash containing the corresponding voter record or nil if not found: { :voter_record, :voters_field_names, :upload }
  #
  def get_voter_record(beta)
    voter_record       = nil
    voters_field_names = nil

    # Get the retrieved voter public keys file and the associated field.
    voters = @election.uploads.find_by(file_type: FileType.find_by(name: PUBLIC_VOTERS_KEYS))

    if voters
      voters_field_names = voters.get_field_names
      beta_field         = voters.field_name_to_sym(BETA_FIELD)

      if beta_field
        voter_record = voters.contents.find_by(beta_field => beta)
      end
    end

    { voter_record: voter_record, voters_field_names: voters_field_names, upload: voters }
  end

  #
  # Setup the election from its name.
  #
  def set_election
    @election = Election.find_by!(name: params[:election])
  end

  #
  # Setup the vote record.
  #
  def set_vote_record
    alpha          = params[:alpha].to_i
    beta           = params[:beta].to_i
    tracker_number = params[:tracker].to_i

    # Get public key from beta and then the corresponding private key.
    @uploads        = []
    public_key_data = get_public_key(beta)
    public_key      = public_key_data[:public_key]
    @uploads << public_key_data[:upload]

    private_key = get_private_key(public_key)

    # Get the election parameter p.
    p = get_p

    # Decrypt the alpha and beta to reveal the tracker number in the group. We use OpenSSL to perform modulo arithmetic on big integers. For further details, please
    # see the private VMV class DecryptTrackerNumberShellComponent and associated cryptographic operations.
    @vote_record        = nil
    @voters_field_names = nil

    if alpha && (alpha > 0) && beta && (beta > 0) && private_key && (private_key > 0) && p && (p > 0)

app/views/verify/faq.en.html.haml
- specific_title [ t('shared.titles.faq') ]
- add_breadcrumb t('shared.titles.faq'), request.path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= t('shared.titles.faq')
  %p Click on the questions below to reveal the answers.

  #accordion
    .card
      .card-header#headingVoted
        .mb-0
          %button.btn.btn-link.btn-lg{ data: { toggle: "collapse", target: "#collapseVoted" }, aria: { expanded: "true", controls: "collapseVoted" } }
            How do you know how I voted?

      #collapseVoted.collapse{ aria: { labelledby: "headingVoted" }, data: { parent: "#accordion" } }
        .card-body
          %p
            We don't.
          %p
            - if @vote_record && @uploads
              Everybody knows that the voter who was assigned tracker number
              %b= @vote_record.send(Content.field_index_to_sym(1))
              voted for
              %b= @vote_record.send(Content.field_index_to_sym(0))
              (in fact, everybody knows each vote for every tracker number, from
              != "#{link_to('this table', upload_contents_path(@uploads.last))},"
              which allows you to check the validity of the announced result), but only you know who that voter is. (ERS also knows, but this is independent to us.)
            - else
              Everybody knows each vote for every tracker number, but only you know who that voter is. (ERS also knows, but this is independent to us.)
          %p
            The
            %i alpha
            and
            %i beta
            parameters in the link you clicked form an encryption of your tracker number. In an ideal world, you would hold the decryption key allowing
            you to retrieve your tracker number and look up your vote in the table. In this trial run, we manage your keys for you, to protect your vote from potential
            breaches into ERS's systems. You can find out more about the design of the system, and the strict separation we enforce between the trust domain for privacy
            and the trust domain for verifiability in our
            != "#{link_to('documentation', documents_path)}."

          %p
            The short version is: ERS knows how you voted, but cannot modify anyone's vote or the results without a chance of being detected; we do not know how you
            voted, and therefore cannot modify your vote without being detected.

    - if @vote_record
      .card
        .card-header#headingReport
          .mb-0
            %button.btn.btn-link.btn-lg{ data: { toggle: "collapse", target: "#collapseReport" }, aria: { expanded: "true", controls: "collapseReport" } }
              What if the checked vote doesn't match what I cast?

        #collapseReport.collapse{ aria: { labelledby: "headingReport" }, data: { parent: "#accordion" } }
          .card-body
            %p
              Please report this to
              != "#{link_to('ERS', verify_report_my_vote_path(election: params[:election], beta: params[:beta], tracker: params[:tracker]))}."

    .card
      .card-header#headingRecords
        .mb-0
          %button.btn.btn-link.btn-lg{ data: { toggle: "collapse", target: "#collapseRecords" }, aria: { expanded: "true", controls: "collapseRecords" } }
            Want to explore the election data?

      #collapseRecords.collapse{ aria: { labelledby: "headingRecords" }, data: { parent: "#accordion" } }
        .card-body
          %p
            If you would like, you can browse through the published election data which has been used for verification by selecting a row from the following table.
            - if @vote_record
              In the displayed data, the rows corresponding to your tracker number and your commitment have been highlighted (you may have to scroll through to find them):
          - view_params = nil
          - if (params[:beta] || params[:tracker]) && @vote_record
            - view_params = [{ field: 0, value: params[:beta] }, { field: 1, value: @vote_record.send(Content.field_index_to_sym(1)) }, { field: 1, value: @vote_record.send(Content.field_index_to_sym(1)) }]
          = render partial: 'uploads/list_table', locals: { uploads: @uploads, restricted: true, unsortable: true, view_params: view_params }

app/views/verify/report_my_vote.en.html.haml
- specific_title [ t('shared.titles.report_my_vote') ]
- add_breadcrumb t('shared.titles.report_my_vote'), request.path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= t('shared.titles.report_my_vote')

  - if params[:election] && (params[:beta] || params[:tracker])
    %p.lead
      Use this page to report a problem with the vote you checked and the vote you cast.
  - else
    %p.lead
      Unfortunately, we could not find a record of your vote using the data that you supplied. This could be because the data has not yet been published, because
      you did not vote, or because the data you have provided is incorrect, for example if you did not correctly copy the web link you were provided.

- if params[:election] && (params[:beta] || params[:tracker])
  .container
    = form_tag verify_send_report_path(election: params[:election], beta: params[:beta], tracker: params[:tracker]), class: 'form' do
      .row
        .col-sm-2
          = label_tag :reason, 'Reason', class: 'mt-2'
        .col-sm-8
          = text_area_tag :reason, nil, placeholder: 'Please enter a reason for your report and include your email address so that we can contact you...', required: true, class: 'form-control'
        .col-sm-2
          = submit_tag 'Send', class: 'btn btn-sm btn-primary mt-2', data: { confirm: 'Are you sure that you want to report a possible problem with your vote to ERS?<br/><br/>We will send the contents of this page (including the URL parameters and your reason) to ERS so they can investigate your report. They already hold information about you, this will just serve to flag up the need to look into their systems. They will then get back to you.' }

    %p.my-2
      By clicking the button, you are telling us to send the contents of this page (including the URL parameters) to ERS so they can investigate your report.
      They already hold this information, this will just serve to flag up the need to look into their systems. They will then get back to you.

app/views/verify/status.en.html.haml
- specific_title [ t('shared.titles.status'), @election.name]
- add_breadcrumb t('shared.titles.status'), request.path
- add_breadcrumb @election.name, election_path(@election)
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= @election.name

.container
  - if @voter_record
    %p.lead
      The following is a valid Tracker Commitment (Part 2) for this election:

    .border.rounded.bg-light.my-2
      %p.p-2.break-all= @voter_record.send(Content.field_index_to_sym(0))

    %h2 Voting
    %p
      - if @vote_cast.nil?
        Voting results will be posted after the close of the election.
      - else
        - if @vote_cast
          A vote has been cast using this Tracker Commitment.
        - else
          No vote has been cast using this Tracker Commitment.

  - else
    %p.lead
      Unfortunately, we could not find a record of this Tracker Commitment (Part 2) using the data that you supplied. This could be because the data you have
      provided is incorrect, for example if you did not correctly copy the web link you were provided.

app/views/verify/verify.en.html.haml
- specific_title [ t('shared.titles.verify'), @election.name]
- add_breadcrumb t('shared.titles.verify'), request.path
- add_breadcrumb @election.name, election_path(@election)
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= @election.name

.container
  - if @vote_record && @voters_field_names
    %p.lead
      This shows the vote as submitted to
      = link_to(t('ers'), t('ers_web'), target: '_blank')
      (ERS) which matches the verification data you supplied:

    %dl.row
      %dt.col-sm-3.text-right Your Vote:
      %dd.col-sm-9.text-left= @vote_record.send(Content.field_index_to_sym(0))

    %dl.row
      %dt.col-sm-3.text-right Tracker Number:
      %dd.col-sm-9.text-left= @vote_record.send(Content.field_index_to_sym(1))
  - else
    %p.lead
      Unfortunately, we could not find a record of your vote using the data that you supplied. This could be because the data has not yet been published, because
      you did not vote, or because the data you have provided is incorrect, for example if you did not correctly copy the web link you were provided.

.container
  - unless @election.survey_url.blank?
    .row
      .col-sm-10
        %p.lead
          We are running a short questionnaire as part of the research trial of this system. Further information about the research trial is available
          != "#{link_to('here', asset_path('survey.pdf'), target: '_blank')}."
          We are very interested in receiving your feedback.
      .col-sm-2
        %p.lead.text-center= link_to('Provide Feedback', @election.survey_url, target: '_blank', class: 'btn btn-lg btn-primary')

.container
  - view_params = nil
  - if (params[:beta] || params[:tracker]) && @vote_record
    - view_params = { field: 1, value: @vote_record.send(Content.field_index_to_sym(1)) }

  %h4= link_to('See all votes', upload_contents_path(@uploads.last, view_params))
  %p The record of all votes received, together with their tracking numbers, including yours.  Use this to check the result.

  %h4= link_to('How does it work?', introduction_path)
  %p An explanation of the design behind the system.

  - if @vote_record
    %h4= link_to('Report if this is not your vote', verify_report_my_vote_path(election: params[:election], beta: params[:beta], tracker: params[:tracker]))
    %p If the vote shown here does not correspond to the vote you cast.

  %h4= link_to('Frequently asked questions', verify_faq_path(election: params[:election], alpha: params[:alpha], beta: params[:beta], tracker: params[:tracker]))
  %p Answers to specific questions about the system.