config/routes.rb
#
# Application routes file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

Rails.application.routes.draw do

  # Provide a route for robots.txt.
  mount_roboto

  # Provide the Devise routes.
  devise_for :users,
             path:        '',
             path_names:  { sign_in:      'login',
                            sign_out:     'logout',
                            registration: 'registration',
                            sign_up:      'sign_up_account' },
             controllers: { registrations: 'users/registrations' }

  # Define the home, about and privacy pages.  Note that root is especially needed for Devise.
  get 'home', to: 'home#home', as: 'home'
  get 'about', to: 'home#about', as: 'about'
  get 'documents', to: 'home#documents', as: 'documents'
  get 'introduction', to: 'home#introduction', as: 'introduction'
  get 'privacy', to: 'home#privacy', as: 'privacy'
  get 'verifiable', to: 'home#verifiable', as: 'verifiable'
  root to: redirect(path: '/home')

  # Define user account pages.
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :invitations, except: [:show]

  # Define service pages.
  resources :services, only: [:edit, :update]

  # Define election pages and associated data.
  resources :audit_logs, only: [:index]
  resources :file_types
  resources :elections
  resources :uploads, except: [:destroy] do
    resources :contents, shallow: true, only: [:index, :show]
    member do
      get :blockchain
      get :download
      post :recommit
      post :retrieve
    end
  end

  # Define the voter verification routes.
  get 'verify', to: 'verify#verify'
  get 'verify/status', to: 'verify#status'
  get 'verify/faq', to: 'verify#faq'
  get 'verify/report_my_vote', to: 'verify#report_my_vote'
  post 'verify/send_report', to: 'verify#send_report'

  # Match certbot challenge responses.
  get '/.well-known/acme-challenge/*file', to: 'home#challenge', as: 'challenge'

  # Catch anything else and send it to the UI root, unless in development mode. Note that we explicitly ignore ActiveStorage as its routes are added afterwards.
  unless Rails.env.development?
    match "*path", to: 'application#not_found', via: :all, constraints: lambda { |request|
      request.path.exclude? 'rails/active_storage'
    }
  end
end

app/models/upload.rb
#
# Upload model file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

class Upload < ApplicationRecord
  include Public
  include Job

  # Associations.
  belongs_to :file_type, inverse_of: :uploads
  belongs_to :election, inverse_of: :uploads, touch: true
  has_many :contents, inverse_of: :upload, dependent: :destroy

  # Attachments.
  has_one_attached :file

  # Validators.
  validates :file, attached: true
  validates :address, :checksum, presence: true, if: -> { self.success? }
  validates :public, inclusion: { in: [false], message: I18n.t('activerecord.errors.models.upload.attributes.public') }, if: -> { !self.file_type&.public? }

  # Scopes.
  scope :to_retrieve, -> (age) do
    joins(:file_type)
      .where(public: true)
      .where('file_types.convert_to_content = ? AND uploads.address is not null AND (retrieved_at <= ? OR retrieved_at is NULL)', true, Time.current - age)
      .order(Arel.sql('CASE WHEN retrieved_at IS NULL THEN 0 ELSE 1 END, retrieved_at ASC, created_at ASC'))
  end

  #
  # Downloads the copy of the file attachment from the blockchain.
  #
  # @return A hash containing { io: the content of the file as an IO object, filename: the original file name, content_type: the content type, checksum: a checksum of the data, file: the associated file wrapper }.
  #
  def download_from_blockchain!
    result = nil

    if self.file_type
      # The download process depends upon the type of file and is performed against a random Quorum node.
      file_wrapper = QuorumFileHelper.wrapper_for_content(self.file_type.content_type)
      url          = Service.get_service.get_random_node

      if url && self.address
        # Perform the download.
        helper = QuorumFileHelper.new(url)
        file   = helper.get(self.address, file_wrapper)
        result = file.get(self.checksum)

        if result[:checksum] == self.checksum
          result[:io]   = StringIO.new(self.file.download)
          result[:file] = file
        else
          result = nil
        end
      end
    end

    result
  end

  #
  # Attempts to convert a field name into its corresponding field symbol.
  #
  # @param name The name of the field.
  # @return The symbol of the content field given its name.
  #
  def field_name_to_sym(name)
    field_names = self.get_field_names
    index       = field_names.find_index(name) if field_names
    index.nil? ? nil : Content.field_index_to_sym(index)
  end

  #
  # @return The names of the fields for the content from the first sequence associated with the upload. Assumes that the content has been loaded.
  #
  def get_field_names
    names  = nil
    header = self.contents.first

    if header
      field_keys = header.attributes.keys.sort.select { |k| k =~ /\Afield.*/ }
      names      = []

      field_keys.each do |field|
        names << header.attributes[field]
      end
    end

    names
  end

  #
  # Updates the associated content for the upload with the content of the file from the blockchain. This only works for content of an appropriate type.
  #
  def update_content!
    result = false

    if self&.file_type&.convert_to_content?
      content = self.download_from_blockchain!

      if content && content[:io] && content[:file]
        ActiveRecord::Base.transaction do
          # Destroy all existing content for the upload.
          self.contents.destroy_all

          # Update the content from the downloaded file.
          lines = content[:file].convert(content[:io])

          lines.each_with_index do |line, i|
            content = self.contents.new(sequence: i)

            line.each_with_index do |value, j|
              content[Content.field_index_to_sym(j)] = value
            end

            content.save!
            result = true
          end

          self.update!(retrieved_at: Time.current)
        end
      end
    else
      result = true
    end

    result
  end

  #
  # Uploads the file attachment to the blockchain.
  #
  # @return A hash containing { filename: the content file name, content_type: the content type, checksum: a checksum of the file, file: the associated file wrapper }.
  #
  def upload_to_blockchain!
    result = nil

    if self.file_type
      # The upload process depends upon the type of file and is performed against a random Quorum node.
      file_wrapper = QuorumFileHelper.wrapper_for_content(self.file_type.content_type)
      url          = Service.get_service.get_random_node

      if url && self.file.attached?
        # Perform the upload and record the contract address.
        helper        = QuorumFileHelper.new(url)
        file          = helper.create(file_wrapper)
        result        = file.add(self.file.filename, self.file_type.content_type, StringIO.new(self.file.download))
        result[:file] = file
        self.update!(address: file.contract.address, checksum: result[:checksum])
      end
    end

    result
  end
end

app/controllers/uploads_controller.rb
#
# Uploads controller class.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :blockchain, :download, :edit, :update, :recommit, :retrieve]
  before_action :authenticate_user!, except: [:blockchain, :download]
  before_action :set_show_account, except: [:blockchain, :download]
  before_action :set_election, only: [:index]

  #
  # GET /uploads/1/blockchain
  #
  def blockchain
    authorize @upload.election, :show?
    authorize @upload

    # Obtain blockchain version of file and send it back.
    content = nil
    content = @upload.download_from_blockchain! if @upload.address

    if content && content[:io]
      send_data content[:io].read, filename: @upload.file.filename, type: @upload.file_type.content_type, disposition: 'attachment', status: :ok
    else
      redirect_to root_path, alert: I18n.t('uploads.messages.no_blockchain_attachment')
    end
  end

  #
  # GET /uploads/1/download
  #
  def download
    authorize @upload.election, :show?
    authorize @upload

    # Obtain the ActiveStorage version of the file and send it back.
    if @upload.file.attached?
      send_data @upload.file.download, filename: @upload.file.filename, type: @upload.file_type.content_type, disposition: 'attachment', status: :ok
    else
      redirect_to root_path, alert: I18n.t('uploads.messages.no_download_attachment')
    end
  end

  #
  # GET /uploads
  # GET /uploads.js
  #
  def index
    # Optionally filter by election.
    if @election
      @uploads = policy_scope(Upload).where(election: @election).joins(:file_type).order(sort_column.to_s + ' ' + sort_direction.to_s).page(params[:page]).per(params[:limit])
    else
      @uploads = policy_scope(Upload).joins(:file_type).order(sort_column.to_s + ' ' + sort_direction.to_s).page(params[:page]).per(params[:limit])
    end

    authorize @uploads
  end

  #
  # GET /uploads/1
  #
  def show
    authorize @upload
  end

  #
  # GET /uploads/new
  #
  def new
    @upload = Upload.new
    authorize @upload
  end

  #
  # GET /uploads/1/edit
  #
  def edit
    authorize @upload
  end

  #
  # POST /uploads
  #
  def create
    @upload = Upload.new(upload_params)
    authorize @upload

    respond_to do |format|
      if @upload.save
        commit_file
        format.html { redirect_to uploads_url, notice: I18n.t('shared.messages.created') }
      else
        format.html { render :new }
      end
    end
  end

  #
  # PATCH/PUT /uploads/1
  #
  def update
    authorize @upload

    respond_to do |format|
      if @upload.update(upload_params)
        commit_file
        format.html { redirect_to uploads_url, notice: I18n.t('shared.messages.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  #
  # POST /images/1/recommit
  #
  def recommit
    authorize @upload

    respond_to do |format|
      commit_file
      format.html { redirect_to uploads_url, notice: I18n.t('uploads.messages.recommit') }
    end
  end

  #
  # POST /images/1/retrieve
  #
  def retrieve
    authorize @upload

    respond_to do |format|
      retrieve_file
      format.html { redirect_to uploads_url, notice: I18n.t('uploads.messages.retrieve') }
    end
  end

  private

  #
  # Determines if the uploaded file should be committed to the blockchain and if so, commits it.
  #
  def commit_file
    if @upload.public? && @upload.file_type.public? && @upload.address.blank? && (@upload.creating? || @upload.failed?)
      BlockchainCommitJob.perform_later(@upload.id)
    end
  end

  #
  # Determines if the uploaded file can be retrieved from the blockchain and if so, retrieves it.
  #
  def retrieve_file
    if @upload.public? && @upload.file_type.public? && @upload.address.present? && @upload.success?
      BlockchainRetrieveJob.perform_later(@upload.id)
    end
  end

  #
  # Setup the parent resource.
  #
  def set_election
    @election = nil
    @election = Election.find(params[:filter]) if params[:filter]
    @election = Election.find(params[:election_id]) if params[:election_id]
  end

  #
  # Setup the resource.
  #
  def set_upload
    @upload = Upload.find(params[:id])
  end

  #
  # Never trust parameters from the scary Internet, only allow the white list through.
  #
  def upload_params
    params.require(:upload).permit(:election_id, :file_type_id, :public, :file) # Not status, address or checksum.
  end

  #
  # Add in helper method for sort column.
  #
  helper_method :sort_column

  #
  # @returns The sort column.
  #
  def sort_column
    column = Upload.column_names.include?(params[:sort].to_s) ? params[:sort].to_sym : 'file_types.sequence'.to_sym

    # Deal with the join tables.
    table_columns = params[:sort].to_s.split('.')
    column        = FileType.column_names.include?(table_columns[1].to_s) ? params[:sort].to_sym : column if table_columns.size >= 2 && table_columns[0] == FileType.table_name
    column        = FileType.column_names.include?(table_columns[1].to_s) ? params[:sort].to_sym : column if table_columns.size >= 2 && table_columns[0] == Upload.table_name

    column
  end
end

app/views/uploads/_form.html.haml
- set_page_model(upload)
= bootstrap_form_for(upload, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |form|
  = form_field(form, :select, :election_id, select_options: Election.election_map_select, autofocus: true)
  = form_field(form, :select, :file_type_id, select_options: FileType.file_type_map_select)
  - if upload.new_record?
    = form.file_field :file, direct_upload: true
    :javascript
      var file_type_select = $('#upload_file_type_id');

      function update(target) {
        var content_type = $('option:selected', target).attr('content_type');
        var upload = $('#upload_file');
        upload.attr('accept', content_type);

        var hint = $('option:selected', target).attr('hint');
        if (hint) {
          var label = upload.next('label').html();
          upload.next('label').html(label.replace(/:.*/, '') + ': ' + hint);
        }
        else {
          var label = upload.next('label').html();
          upload.next('label').html(label.replace(/:.*/, ''));
        }
      }

      update(file_type_select);

      file_type_select.change(function() {
        update(this);
      })

  = form.form_group do
    = form_field(form, :check_box, :public)

  = render partial: 'shared/form_mandatory', locals: { form: form }
  = render partial: 'shared/form_buttons', locals: { form: form }

app/views/uploads/_list.html.haml
- if uploads.count > 0
  = paginate uploads, count: uploads.total_count, remote: true if uploads.respond_to?(:total_pages)
  - sortable = false
  - sortable = true unless defined?(unsortable)
  - if sortable
    %p.d-flex.flex-wrap.align-items-center.justify-content-end.h-100
      %span.small= t('shared.controls.sort')
      - restricted = false unless defined?(restricted)
      - unless restricted
        %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:election_id, t('activerecord.attributes.upload.election_id'), filter: params[:filter])
      %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable('file_types.sequence'.to_sym, t('activerecord.attributes.upload.file_type_id'), filter: params[:filter])
      - unless restricted
        %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:status, t('activerecord.attributes.upload.status'), filter: params[:filter])
        %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:'uploads.public', t('activerecord.attributes.upload.public'), filter: params[:filter])
        %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable(:retrieved_at, t('activerecord.attributes.upload.retrieved_at'), filter: params[:filter])
  .row
    - view_params = [] unless defined?(view_params)
    - uploads.each_with_index do |upload, index|
      - extracted_params = view_params[index] if view_params && (view_params.size > index)
      - cache [upload, upload.file_type, upload.election, restricted, extracted_params, user_signed_in?] do
        .col-lg-4.col-md-6.col-12.my-3
          .card.text-white{ class: !upload.file_type.public? ? 'bg-muted-danger' : upload.public? ? 'bg-primary' : 'bg-muted-primary' }
            .card-header.d-flex.justify-content-between
              %span
                = fa_icon(t("activerecord.attributes.file_type.#{upload.file_type.action}.icon"))
                = restricted ? upload.file_type.name : "#{upload.file_type.sequence}. #{upload.file_type.name}"
              = render partial: 'shared/list_buttons', locals: { model: upload, name: upload.file_type.name, options: { css_class: 'text-white no-decoration' } }
            .card-body.px-0
              - if restricted
                %p.card-title.d-flex.flex-row.card-description
                  %span.col.text-wrap= upload.file_type.description
              - else
                %p.card-title.d-flex.flex-row.rounded.mx-1
                  %span.col-5.text-left= t('activerecord.attributes.upload.election_id')
                  %span.col-7.text-right= upload.election.name
                %p.card-title.d-flex.flex-row.rounded.mx-1
                  %span.col-5.text-left= t('activerecord.attributes.file_type.action')
                  %span.col-7.text-right= t("activerecord.attributes.file_type.#{upload.file_type.action}.name")
                %p.card-title.d-flex.flex-row.rounded.mx-1
                  %span.col-3.text-left= t('activerecord.attributes.upload.filename')
                  %span.col-9.text-right
                    - if upload.file.attached?
                      = upload.file.filename.to_s
                %p.card-title.d-flex.flex-row.rounded.mx-1{ class: !upload.public? ? '' : upload.pending? || upload.creating? ? 'bg-secondary' : upload.failed? ? 'bg-danger' : 'bg-success' }
                  %span.col-5.text-left= t('activerecord.attributes.upload.status')
                  %span.col-7.text-right= upload.file_type.public? ? t("activerecord.attributes.job.#{upload.status}") : t('shared.controls.na')
                %p.card-title.d-flex.flex-row.rounded.mx-1{ class: upload.file_type.public? && upload.file_type.convert_to_content? ? (!upload.contents.exists? ? 'bg-danger' : 'bg-success') : '' }
                  %span.col-5.text-left= t('activerecord.attributes.upload.retrieved')
                  %span.col-7.text-right= upload.file_type.public? && upload.file_type.convert_to_content? ? (upload.contents.exists? && upload.retrieved_at ? l(upload.retrieved_at, format: :short) : t('shared.controls.no')) : t('shared.controls.na')
              %p.card-title.d-flex.flex-row.mb-0
                - if user_signed_in?
                  %span.col.text-center= link_to t('shared.controls.details'), upload_path(upload), class: !upload.file_type.public? ? 'btn btn-danger p-0 w-100' : 'btn btn-secondary p-0 w-100'
                - if lookup_context.template_exists?(upload.file_type.action, 'contents', true)
                  %span.col.text-center= link_to t('shared.controls.view'), upload_contents_path(upload, extracted_params), class: !upload.file_type.public? ? 'btn btn-danger p-0 w-100' : 'btn btn-secondary p-0 w-100'

app/views/uploads/_list_table.html.haml
- if uploads.count > 0
  = paginate uploads, count: uploads.total_count, remote: true if uploads.respond_to?(:total_pages)
  - sortable = false
  - sortable = true unless defined?(unsortable)
  - if sortable
    %p.d-flex.flex-wrap.align-items-center.justify-content-end.h-100
      %span.small= t('shared.controls.sort')
      %span.btn.btn-sm.btn-light.ml-1.mt-1= sortable('file_types.sequence'.to_sym, t('activerecord.attributes.upload.file_type_id'))
  - @table_count ||= 0
  - @table_count += 1
  - id = "table-#{@table_count}"
  .row.mb-4
    .table-responsive{ id: id }
      %table.table.table-hover.table-sm.table-bordered
        %thead.thead-light
          %tr
            - unless restricted
              %th
              %th.text-center= sortable ? sortable(:election_id, t('activerecord.attributes.upload.election_id')) : t('activerecord.attributes.upload.election_id')
            %th.text-center= sortable ? sortable('file_types.sequence'.to_sym, t('activerecord.attributes.upload.file_type_id')) : t('activerecord.attributes.upload.file_type_id')
            %th.text-center= t('activerecord.attributes.file_type.description')
        %tbody
          - view_params = [] unless defined?(view_params)
          - uploads.each_with_index do |upload, index|
            - extracted_params = view_params[index] if view_params && (view_params.size > index)
            %tr{ class: !upload.file_type.public? ? 'bg-muted-danger' : upload.public? ? '' : 'bg-muted-primary', data: { href: upload_contents_path(upload, extracted_params) } }
              %td= upload.file_type.name
              %td= upload.file_type.description

  - if uploads.size > 3
    :javascript
      VMV.Table.stickyHeader(".table-responsive##{id}", true);

app/views/uploads/_upload.html.haml
= bootstrap_form_for(upload, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-9') do |form|
  = form_field(form, :text_field, :election_id, value: upload.election.name, disabled: true)
  = form_field(form, :text_field, :file_type_id, value: upload.file_type.name, disabled: true)
  = form_field(form, :text_field, :status, value: t("activerecord.attributes.job.#{upload.status}"), control_col: 'col-sm-3', disabled: true)
  - if upload.file.attached?
    = form_field(form, :text_field, :file, disabled: true, value: upload.file.filename, append: link_to(t('shared.controls.download'), download_upload_path(upload), class: 'btn btn-primary'))
    - if upload.address
      = form_field(form, :text_field, :address, disabled: true)
      = form_field(form, :text_field, :checksum, disabled: true)
      = form_field(form, :text_field, :file, disabled: true, value: upload.file.filename, label: t('activerecord.attributes.upload.blockchain'), append: link_to(t('shared.controls.download'), blockchain_upload_path(upload), class: 'btn btn-primary'))
  = form.form_group do
    = form_field(form, :check_box, :public, disabled: true)

  - if upload.failed? && policy(Upload).recommit?
    = form.form_group do
      = link_to t('shared.controls.recommit'), recommit_upload_path(upload), class: 'btn btn-danger', method: :post, data: { confirm: t('.recommit') } if policy(Upload).recommit?

  - if upload.success? && policy(Upload).retrieve?
    = form.form_group do
      = link_to t('shared.controls.retrieve'), retrieve_upload_path(upload), class: 'btn btn-danger', method: :post, data: { confirm: t('.retrieve') } if policy(Upload).retrieve?

  = render partial: 'shared/show_buttons', locals: { form: form, model: upload, name: upload.file_type.name }

app/views/uploads/edit.html.haml
- specific_title [t('shared.controls.edit'), t('shared.titles.upload')]
- add_breadcrumb "#{@upload.file_type.name}: #{t('shared.controls.edit')}", request.path
- add_breadcrumb t('shared.titles.uploads'), :uploads_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= "#{t('shared.controls.edit')}: #{t('shared.titles.upload')}"
  %p.lead= t('.instructions')

  = render partial: 'form', locals: { upload: @upload }

app/views/uploads/index.html.haml
- specific_title [t('shared.titles.uploads')]
- add_breadcrumb t('shared.titles.uploads'), :uploads_path
- content_for :menu do
  = render 'shared/menu'

.container
  - if @election
    %h1= @election.name
    %h2
      = t('shared.titles.uploads')
      - if policy(Upload).new?
        .float-right= link_to t('shared.controls.new'), new_upload_path, class: 'btn btn-primary'
  - else
    %h1
      = t('shared.titles.uploads')
      - if policy(Upload).new?
        .float-right= link_to t('shared.controls.new'), new_upload_path, class: 'btn btn-primary'

  - if @uploads.count > 0
    %p.lead= t('.instructions')
  - else
    %p.lead= t('.no_uploads')

.container#list
  = render partial: 'list', locals: { uploads: @uploads }

app/views/uploads/index.js.erb
$('#list').html("<%= j render partial: 'list', locals: { uploads: @uploads } %>");

app/views/uploads/new.html.haml
- specific_title [t('shared.controls.new'), t('shared.titles.upload')]
- add_breadcrumb "#{t('shared.titles.upload')}: #{t('shared.controls.new')}", request.path
- add_breadcrumb t('shared.titles.uploads'), :uploads_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= "#{t('shared.controls.new')}: #{t('shared.titles.upload')}"
  %p.lead= t('.instructions')

  = render partial: 'form', locals: { upload: @upload }

app/views/uploads/show.html.haml
- specific_title [@upload.file_type.name, t('shared.titles.upload')]
- add_breadcrumb @upload.file_type.name, request.path
- add_breadcrumb t('shared.titles.uploads'), :uploads_path
- content_for :menu do
  = render 'shared/menu'

.container
  %h1= @upload.file_type.name
  %p.lead= t('.instructions')

  = render partial: 'upload', locals: { upload: @upload }